# Site settings
title: Katherine Anne Porter
email: tmunoz@umd.edu
description: >
  The collected correspondence of American author Katherine Anne Porter.
baseurl: ""
url: "http://dev.katherineanneporter.info"

# Collections
collections:
  correspondents:
    output: true
    path: /correspondents/:path/
# Data
page_gen:
  - data: 'collection-items'
    template: 'item-page'
    name: 'id'
    dir: 'collection/items'

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
exclude: [src, node_modules, webpack.dev.config.js, webpack.prod.config.js, eslint.js, package.json, README.md, LICENSE]
keep_files: [static]
